---
title: "Activity #10: Quarto"
subtitle: "Quarto Questions"
author: "Mutkallam Warraich"
format: html
date: today
self-contained: true
toc: true
---
### Dependencies
```{r}
#| warning: false
library(ggplot2)
library(dplyr)
library(palmerpenguins)
```


# Question 1
```{r, echo = false}
#| echo: false
myFunction <- function(x){
  y <- (cos(4*x) + tan(0.5*x))^4
  return(y)
}

ggplot() +
  stat_function(
    fun = myFunction,
    xlim = c(0, 1),
    n = 1000
  ) +
  theme_bw() +
  labs(
    x = "x",
    y = "h(x)"
  )
```

# Question 2
```{r}
#| echo: true
penguin_summary <- penguins %>%
  group_by(species) %>%
  summarize(average_body_mass = mean(body_mass_g, na.rm = TRUE))
ggplot(penguin_summary, aes(x = species, y = average_body_mass, fill = species)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Average Body Mass by Species",
    x = "Species",
    y = "Average Body Mass"
)
```

# Question 3
```{r}
#| echo: true
data <- read.csv("C:/Users/wmutk/OneDrive/Documents/tortilla_data.csv")
head(data)
```
### A)
```{r}
#| echo: true
avg_price_2007 <- data %>%
  filter(year == 2007) %>%
  summarize(average_price = mean(price, na.rm = TRUE))
avg_price_2007
```
### B)
```{r}
#| echo: true
avg_price_2024 <- data %>%
  filter(year == 2024) %>%
  summarize(average_price = mean(price, na.rm = TRUE))
avg_price_2024
```
### C)
```{r}
#| echo: true
percent_change <- ((avg_price_2024 - avg_price_2007)/avg_price_2007)*100
percent_change
```
### D)
```{r}
#| warning: false
#| echo: true
avg_price <- data %>%
  filter(year >= 2007 & year <= 2024) %>%
  group_by(year) %>%
  summarize(average_price = mean(price, na.rm = TRUE))

# Plot the data
ggplot(avg_price, aes(x = year, y = average_price)) +
  geom_line(color = "red", size = 1) +
  geom_point(size = 2) +
  labs(
    title = "Average Tortilla Price from 2007 to 2024",
    x = "Year",
    y = "Average Price"
  )
```


